import { PrismaClient } from '@prisma/client';
import bcrypt from 'bcryptjs';
import { DEFAULT_ROLES } from '../dist/middleware/rbac.js';

const prisma = new PrismaClient();

async function main() {
  console.log('Seeding database...');

  const roles = {};
  for (const [key, roleDef] of Object.entries(DEFAULT_ROLES)) {
    roles[key] = await prisma.role.upsert({
      where: { name: roleDef.name },
      update: { permissions: roleDef.permissions },
      create: { name: roleDef.name, description: `${roleDef.name} role`, permissions: roleDef.permissions },
    });
  }

  const clinicData = [
    { slug: 'medicine', name: 'Medicine Clinic', type: 'MEDICINE', consultationFee: 150, followUpFee: 100 },
    { slug: 'ent', name: 'ENT Clinic', type: 'ENT', consultationFee: 200, followUpFee: 150 },
    { slug: 'dental', name: 'Dental Clinic', type: 'DENTAL', consultationFee: 250, followUpFee: 180 },
    { slug: 'retina', name: 'Retina Clinic', type: 'RETINA', consultationFee: 300, followUpFee: 200 },
    { slug: 'glaucoma', name: 'Glaucoma Clinic', type: 'GLAUCOMA', consultationFee: 300, followUpFee: 200 },
    { slug: 'orbit', name: 'Orbit Clinic', type: 'ORBIT', consultationFee: 350, followUpFee: 250 },
    { slug: 'pediatrics-ophth', name: 'Pediatrics Ophthalmology', type: 'PEDS_OPHTH', consultationFee: 250, followUpFee: 180 },
    { slug: 'general-ophth', name: 'General Ophthalmology', type: 'GEN_OPHTH', consultationFee: 200, followUpFee: 150 },
    { slug: 'optometry', name: 'Optometry Clinic', type: 'OPTOMETRY', consultationFee: 100, followUpFee: 75 },
  ];
  const clinics = await Promise.all(
    clinicData.map(({ slug, name, type, consultationFee, followUpFee }) =>
      prisma.clinic.upsert({
        where: { slug },
        update: { consultationFee, followUpFee },
        create: { name, slug, type, consultationFee, followUpFee },
      }),
    ),
  );

  const passwordHash = await bcrypt.hash('password123', 12);

  await prisma.user.upsert({
    where: { email: 'admin@aljawarih.sd' },
    update: {},
    create: {
      email: 'admin@aljawarih.sd',
      passwordHash,
      fullName: 'Admin User',
      roleId: roles.SUPER_ADMIN.id,
    },
  });

  const doctorClinicPairs = [
    { email: 'doctor.medicine@aljawarih.sd', name: 'Dr. Ahmed', clinicIdx: 0 },
    { email: 'doctor.ent@aljawarih.sd', name: 'Dr. Fatima', clinicIdx: 1 },
    { email: 'doctor.dental@aljawarih.sd', name: 'Dr. Hassan', clinicIdx: 2 },
    { email: 'doctor.retina@aljawarih.sd', name: 'Dr. Noor', clinicIdx: 3 },
    { email: 'doctor.glaucoma@aljawarih.sd', name: 'Dr. Layla', clinicIdx: 4 },
    { email: 'doctor.orbit@aljawarih.sd', name: 'Dr. Omar', clinicIdx: 5 },
    { email: 'doctor.peds@aljawarih.sd', name: 'Dr. Sara', clinicIdx: 6 },
    { email: 'doctor.ophth@aljawarih.sd', name: 'Dr. Khalid', clinicIdx: 7 },
    { email: 'doctor.optometry@aljawarih.sd', name: 'Dr. Mariam', clinicIdx: 8 },
  ];

  for (const pair of doctorClinicPairs) {
    await prisma.user.upsert({
      where: { email: pair.email },
      update: {},
      create: {
        email: pair.email,
        passwordHash,
        fullName: pair.name,
        roleId: roles.DOCTOR.id,
        clinicId: clinics[pair.clinicIdx].id,
      },
    });
  }

  await prisma.user.upsert({
    where: { email: 'reception@aljawarih.sd' },
    update: {},
    create: {
      email: 'reception@aljawarih.sd',
      passwordHash,
      fullName: 'Reception Staff',
      roleId: roles.RECEPTIONIST.id,
    },
  });

  await prisma.user.upsert({
    where: { email: 'lab.tech@aljawarih.sd' },
    update: {},
    create: {
      email: 'lab.tech@aljawarih.sd',
      passwordHash,
      fullName: 'Lab Technician',
      roleId: roles.LAB_TECHNICIAN.id,
    },
  });

  await prisma.user.upsert({
    where: { email: 'pharmacy@aljawarih.sd' },
    update: {},
    create: {
      email: 'pharmacy@aljawarih.sd',
      passwordHash,
      fullName: 'Pharmacist',
      roleId: roles.PHARMACIST.id,
    },
  });

  await prisma.user.upsert({
    where: { email: 'optics@aljawarih.sd' },
    update: {},
    create: {
      email: 'optics@aljawarih.sd',
      passwordHash,
      fullName: 'Optician',
      roleId: roles.OPTICIAN.id,
    },
  });

  await prisma.user.upsert({
    where: { email: 'procurement@aljawarih.sd' },
    update: {},
    create: {
      email: 'procurement@aljawarih.sd',
      passwordHash,
      fullName: 'Procurement Manager',
      roleId: roles.PROCUREMENT_MANAGER.id,
    },
  });

  await prisma.user.upsert({
    where: { email: 'cfo@aljawarih.sd' },
    update: {},
    create: {
      email: 'cfo@aljawarih.sd',
      passwordHash,
      fullName: 'CFO User',
      roleId: roles.CFO.id,
    },
  });

  const icd10Codes = [
    { code: 'E11.9', name: 'Type 2 diabetes mellitus without complications', category: 'Endocrine' },
    { code: 'E10.9', name: 'Type 1 diabetes mellitus without complications', category: 'Endocrine' },
    { code: 'E78.5', name: 'Hyperlipidemia, unspecified', category: 'Endocrine' },
    { code: 'E03.9', name: 'Hypothyroidism, unspecified', category: 'Endocrine' },
    { code: 'E66.9', name: 'Obesity, unspecified', category: 'Endocrine' },
    { code: 'I10', name: 'Essential (primary) hypertension', category: 'Cardiovascular' },
    { code: 'I11.9', name: 'Hypertensive heart disease without heart failure', category: 'Cardiovascular' },
    { code: 'I48', name: 'Atrial fibrillation and flutter', category: 'Cardiovascular' },
    { code: 'I25.10', name: 'Atherosclerotic heart disease of native coronary artery', category: 'Cardiovascular' },
    { code: 'I50.9', name: 'Heart failure, unspecified', category: 'Cardiovascular' },
    { code: 'I20.9', name: 'Angina pectoris, unspecified', category: 'Cardiovascular' },
    { code: 'I64', name: 'Stroke, not specified as hemorrhage or infarction', category: 'Cardiovascular' },
    { code: 'I83.9', name: 'Varicose veins of lower extremities', category: 'Cardiovascular' },
    { code: 'J45.40', name: 'Moderate persistent asthma, uncomplicated', category: 'Respiratory' },
    { code: 'J44.9', name: 'Chronic obstructive pulmonary disease, unspecified', category: 'Respiratory' },
    { code: 'J15.9', name: 'Unspecified bacterial pneumonia', category: 'Respiratory' },
    { code: 'J20.9', name: 'Acute bronchitis, unspecified', category: 'Respiratory' },
    { code: 'J06.9', name: 'Acute upper respiratory infection, unspecified', category: 'Respiratory' },
    { code: 'K21.9', name: 'Gastro-esophageal reflux disease without esophagitis', category: 'Gastrointestinal' },
    { code: 'K29.70', name: 'Gastritis, unspecified, without bleeding', category: 'Gastrointestinal' },
    { code: 'K59.00', name: 'Constipation, unspecified', category: 'Gastrointestinal' },
    { code: 'K76.0', name: 'Fatty (change of) liver, not elsewhere classified', category: 'Gastrointestinal' },
    { code: 'N39.0', name: 'Urinary tract infection, site not specified', category: 'Genitourinary' },
    { code: 'N18.9', name: 'Chronic kidney disease, unspecified', category: 'Genitourinary' },
    { code: 'N20.0', name: 'Calculus of kidney', category: 'Genitourinary' },
    { code: 'M54.5', name: 'Low back pain', category: 'Musculoskeletal' },
    { code: 'M19.90', name: 'Osteoarthritis, unspecified site', category: 'Musculoskeletal' },
    { code: 'M81.0', name: 'Age-related osteoporosis without current pathological fracture', category: 'Musculoskeletal' },
    { code: 'M10.00', name: 'Idiopathic gout', category: 'Musculoskeletal' },
    { code: 'G40.909', name: 'Epilepsy, unspecified, not intractable', category: 'Neurological' },
    { code: 'G43.909', name: 'Migraine, unspecified, not intractable', category: 'Neurological' },
    { code: 'G47.00', name: 'Insomnia, unspecified', category: 'Neurological' },
    { code: 'F32.9', name: 'Major depressive disorder, single episode, unspecified', category: 'Mental Health' },
    { code: 'F41.1', name: 'Generalized anxiety disorder', category: 'Mental Health' },
    { code: 'F43.10', name: 'Post-traumatic stress disorder, unspecified', category: 'Mental Health' },
    { code: 'D50.9', name: 'Iron deficiency anemia, unspecified', category: 'Hematology' },
    { code: 'D64.9', name: 'Anemia, unspecified', category: 'Hematology' },
    { code: 'L30.9', name: 'Dermatitis, unspecified', category: 'Dermatology' },
    { code: 'L03.90', name: 'Cellulitis, unspecified', category: 'Dermatology' },
    { code: 'H10.9', name: 'Conjunctivitis, unspecified', category: 'Ophthalmology' },
    { code: 'H66.90', name: 'Acute otitis media, unspecified', category: 'ENT - Ear' },
    { code: 'H66.91', name: 'Acute otitis media, right ear', category: 'ENT - Ear' },
    { code: 'H66.92', name: 'Acute otitis media, left ear', category: 'ENT - Ear' },
    { code: 'H66.93', name: 'Acute otitis media, bilateral', category: 'ENT - Ear' },
    { code: 'H66.1', name: 'Chronic suppurative otitis media', category: 'ENT - Ear' },
    { code: 'H65.0', name: 'Acute serous otitis media', category: 'ENT - Ear' },
    { code: 'H65.2', name: 'Chronic serous otitis media', category: 'ENT - Ear' },
    { code: 'H60.90', name: 'Otitis externa, unspecified', category: 'ENT - Ear' },
    { code: 'H61.23', name: 'Impacted cerumen', category: 'ENT - Ear' },
    { code: 'H93.1', name: 'Tinnitus', category: 'ENT - Ear' },
    { code: 'H91.9', name: 'Hearing loss, unspecified', category: 'ENT - Ear' },
    { code: 'H91.1', name: 'Presbycusis', category: 'ENT - Ear' },
    { code: 'H90.3', name: 'Sensorineural hearing loss, bilateral', category: 'ENT - Ear' },
    { code: 'H81.0', name: 'Meniere disease', category: 'ENT - Ear' },
    { code: 'H81.1', name: 'Benign paroxysmal positional vertigo', category: 'ENT - Ear' },
    { code: 'H81.2', name: 'Vestibular neuritis', category: 'ENT - Ear' },
    { code: 'H69.8', name: 'Eustachian tube dysfunction', category: 'ENT - Ear' },
    { code: 'H72.90', name: 'Tympanic membrane perforation, unspecified', category: 'ENT - Ear' },
    { code: 'H92.9', name: 'Unspecified ear disorder', category: 'ENT - Ear' },
    { code: 'J01.90', name: 'Acute sinusitis, unspecified', category: 'ENT - Nose/Sinus' },
    { code: 'J32.9', name: 'Chronic sinusitis, unspecified', category: 'ENT - Nose/Sinus' },
    { code: 'J32.0', name: 'Chronic maxillary sinusitis', category: 'ENT - Nose/Sinus' },
    { code: 'J30.4', name: 'Allergic rhinitis', category: 'ENT - Nose/Sinus' },
    { code: 'J33.9', name: 'Nasal polyp, unspecified', category: 'ENT - Nose/Sinus' },
    { code: 'J34.2', name: 'Deviated nasal septum', category: 'ENT - Nose/Sinus' },
    { code: 'J34.3', name: 'Hypertrophy of nasal turbinates', category: 'ENT - Nose/Sinus' },
    { code: 'J34.89', name: 'Other specified disorders of nose and nasal sinuses', category: 'ENT - Nose/Sinus' },
    { code: 'R04.0', name: 'Epistaxis', category: 'ENT - Nose/Sinus' },
    { code: 'R43.0', name: 'Anosmia', category: 'ENT - Nose/Sinus' },
    { code: 'J34.9', name: 'Unspecified nasal disorder', category: 'ENT - Nose/Sinus' },
    { code: 'J02.9', name: 'Acute pharyngitis, unspecified', category: 'ENT - Throat' },
    { code: 'J02.0', name: 'Streptococcal pharyngitis', category: 'ENT - Throat' },
    { code: 'J03.90', name: 'Acute tonsillitis, unspecified', category: 'ENT - Throat' },
    { code: 'J35.01', name: 'Chronic tonsillitis', category: 'ENT - Throat' },
    { code: 'J35.3', name: 'Hypertrophy of tonsils and adenoids', category: 'ENT - Throat' },
    { code: 'J04.0', name: 'Acute laryngitis', category: 'ENT - Throat' },
    { code: 'J37.0', name: 'Chronic laryngitis', category: 'ENT - Throat' },
    { code: 'J38.1', name: 'Vocal cord nodule or polyp', category: 'ENT - Throat' },
    { code: 'J38.0', name: 'Vocal cord paralysis', category: 'ENT - Throat' },
    { code: 'J36', name: 'Peritonsillar abscess', category: 'ENT - Throat' },
    { code: 'R13.0', name: 'Dysphagia, unspecified', category: 'ENT - Throat' },
    { code: 'R07.0', name: 'Pain in throat, unspecified', category: 'ENT - Throat' },
    { code: 'R59.0', name: 'Localized enlarged lymph nodes', category: 'ENT - Neck' },
    { code: 'G47.33', name: 'Obstructive sleep apnea', category: 'ENT - Sleep' },
    { code: 'M26.60', name: 'Temporomandibular joint disorder, unspecified', category: 'ENT - TMJ' },
    { code: 'I78.0', name: 'Hereditary hemorrhagic telangiectasia', category: 'ENT - Vascular' },
    { code: 'R05', name: 'Cough', category: 'ENT - Symptoms' },
    { code: 'K02.9', name: 'Dental caries, unspecified', category: 'Dental - Caries' },
    { code: 'K02.51', name: 'Pit/fissure caries limited to enamel', category: 'Dental - Caries' },
    { code: 'K02.52', name: 'Pit/fissure caries penetrating into dentin', category: 'Dental - Caries' },
    { code: 'K02.53', name: 'Pit/fissure caries penetrating into pulp', category: 'Dental - Caries' },
    { code: 'K02.61', name: 'Smooth surface caries limited to enamel', category: 'Dental - Caries' },
    { code: 'K02.62', name: 'Smooth surface caries penetrating into dentin', category: 'Dental - Caries' },
    { code: 'K02.63', name: 'Smooth surface caries penetrating into pulp', category: 'Dental - Caries' },
    { code: 'K02.7', name: 'Dental root caries', category: 'Dental - Caries' },
    { code: 'K02.3', name: 'Arrested dental caries', category: 'Dental - Caries' },
    { code: 'K04.01', name: 'Reversible pulpitis', category: 'Dental - Pulp/Periapical' },
    { code: 'K04.02', name: 'Irreversible pulpitis', category: 'Dental - Pulp/Periapical' },
    { code: 'K04.1', name: 'Necrosis of pulp', category: 'Dental - Pulp/Periapical' },
    { code: 'K04.4', name: 'Acute apical periodontitis of pulpal origin', category: 'Dental - Pulp/Periapical' },
    { code: 'K04.5', name: 'Chronic apical periodontitis', category: 'Dental - Pulp/Periapical' },
    { code: 'K04.6', name: 'Periapical abscess with sinus', category: 'Dental - Pulp/Periapical' },
    { code: 'K04.7', name: 'Periapical abscess without sinus', category: 'Dental - Pulp/Periapical' },
    { code: 'K04.8', name: 'Radicular cyst', category: 'Dental - Pulp/Periapical' },
    { code: 'K05.00', name: 'Acute gingivitis, plaque induced', category: 'Dental - Periodontal' },
    { code: 'K05.10', name: 'Chronic gingivitis, plaque induced', category: 'Dental - Periodontal' },
    { code: 'K05.20', name: 'Aggressive periodontitis, unspecified', category: 'Dental - Periodontal' },
    { code: 'K05.30', name: 'Chronic periodontitis, unspecified', category: 'Dental - Periodontal' },
    { code: 'K05.311', name: 'Chronic periodontitis, localized slight', category: 'Dental - Periodontal' },
    { code: 'K05.312', name: 'Chronic periodontitis, localized moderate', category: 'Dental - Periodontal' },
    { code: 'K05.313', name: 'Chronic periodontitis, localized severe', category: 'Dental - Periodontal' },
    { code: 'K05.321', name: 'Chronic periodontitis, generalized slight', category: 'Dental - Periodontal' },
    { code: 'K05.322', name: 'Chronic periodontitis, generalized moderate', category: 'Dental - Periodontal' },
    { code: 'K05.323', name: 'Chronic periodontitis, generalized severe', category: 'Dental - Periodontal' },
    { code: 'K05.4', name: 'Periodontosis', category: 'Dental - Periodontal' },
    { code: 'K05.6', name: 'Periodontal disease, unspecified', category: 'Dental - Periodontal' },
    { code: 'K08.0', name: 'Exfoliation of teeth due to systemic causes', category: 'Dental - Tooth Loss' },
    { code: 'K08.3', name: 'Retained dental root', category: 'Dental - Tooth Loss' },
    { code: 'K08.411', name: 'Partial loss of teeth due to trauma class I', category: 'Dental - Tooth Loss' },
    { code: 'K08.111', name: 'Complete loss of teeth due to trauma class I', category: 'Dental - Tooth Loss' },
    { code: 'K08.50', name: 'Defective dental restoration, unspecified', category: 'Dental - Restoration' },
    { code: 'K08.51', name: 'Open margins of dental restoration', category: 'Dental - Restoration' },
    { code: 'K08.530', name: 'Fractured dental restoration', category: 'Dental - Restoration' },
    { code: 'K12.0', name: 'Recurrent oral aphthae', category: 'Dental - Oral Mucosa' },
    { code: 'K12.2', name: 'Cellulitis and abscess of mouth', category: 'Dental - Oral Mucosa' },
    { code: 'K12.30', name: 'Oral mucositis, unspecified', category: 'Dental - Oral Mucosa' },
    { code: 'K13.0', name: 'Diseases of lips', category: 'Dental - Oral Mucosa' },
    { code: 'K13.21', name: 'Leukoplakia of oral mucosa', category: 'Dental - Oral Mucosa' },
    { code: 'K13.3', name: 'Hairy leukoplakia', category: 'Dental - Oral Mucosa' },
    { code: 'K13.5', name: 'Oral submucous fibrosis', category: 'Dental - Oral Mucosa' },
    { code: 'K07.6', name: 'Temporomandibular joint disorders', category: 'Dental - TMJ' },
    { code: 'K11.20', name: 'Sialoadenitis, unspecified', category: 'Dental - Salivary' },
    { code: 'K11.5', name: 'Sialolithiasis (salivary stone)', category: 'Dental - Salivary' },
    { code: 'K11.6', name: 'Mucocele of salivary gland', category: 'Dental - Salivary' },
    { code: 'K11.7', name: 'Disturbances of salivary secretion', category: 'Dental - Salivary' },
    { code: 'K00.0', name: 'Anodontia', category: 'Dental - Developmental' },
    { code: 'K00.1', name: 'Supernumerary teeth', category: 'Dental - Developmental' },
    { code: 'K00.6', name: 'Disturbances in tooth eruption', category: 'Dental - Developmental' },
    { code: 'K01.0', name: 'Embedded teeth', category: 'Dental - Developmental' },
    { code: 'K01.1', name: 'Impacted teeth', category: 'Dental - Developmental' },
    { code: 'K03.0', name: 'Excessive attrition of teeth', category: 'Dental - Non-caries' },
    { code: 'K03.1', name: 'Abrasion of teeth', category: 'Dental - Non-caries' },
    { code: 'K03.2', name: 'Erosion of teeth', category: 'Dental - Non-caries' },
    { code: 'K03.81', name: 'Cracked tooth', category: 'Dental - Non-caries' },
    { code: 'K06.0', name: 'Gingival recession', category: 'Dental - Gingival' },
    { code: 'K06.1', name: 'Gingival enlargement', category: 'Dental - Gingival' },
    { code: 'K09.0', name: 'Developmental odontogenic cysts', category: 'Dental - Cysts' },
    { code: 'K10.0', name: 'Developmental disorders of jaws', category: 'Dental - Jaw' },
    { code: 'K10.2', name: 'Inflammatory conditions of jaws', category: 'Dental - Jaw' },
    { code: 'M27.3', name: 'Alveolitis of jaws (dry socket)', category: 'Dental - Jaw' },
    { code: 'M27.61', name: 'Osseointegration failure of dental implant', category: 'Dental - Implant' },
    { code: 'S02.5XXA', name: 'Fracture of tooth, initial encounter', category: 'Dental - Trauma' },
    { code: 'K14.0', name: 'Glossitis', category: 'Dental - Tongue' },
    { code: 'K14.1', name: 'Geographic tongue', category: 'Dental - Tongue' },
    { code: 'K14.6', name: 'Glossodynia', category: 'Dental - Tongue' },
    { code: 'Z01.2', name: 'Dental examination with normal findings', category: 'Dental - Exam' },
    { code: 'Z01.21', name: 'Dental examination with abnormal findings', category: 'Dental - Exam' },
    { code: 'Z41.8', name: 'Encounter for prophylactic dental procedure', category: 'Dental - Prevention' },
    { code: 'Z00.00', name: 'Encounter for general adult medical examination without abnormal findings', category: 'Preventive' },
    { code: 'Z01.30', name: 'Encounter for examination of blood pressure with abnormal findings', category: 'Preventive' },
    { code: 'Z23', name: 'Encounter for immunization', category: 'Preventive' },
    { code: 'Z86.39', name: 'Personal history of other endocrine, nutritional and metabolic disease', category: 'History' },
    { code: 'Z86.72', name: 'Personal history of atrial fibrillation', category: 'History' },
    { code: 'Z79.4', name: 'Long term (current) use of insulin', category: 'Medication' },
    { code: 'Z79.82', name: 'Long term (current) use of aspirin', category: 'Medication' },
    { code: 'Z79.01', name: 'Long term (current) use of anticoagulants', category: 'Medication' },
    { code: 'R05', name: 'Cough', category: 'Symptoms' },
    { code: 'R50.9', name: 'Fever, unspecified', category: 'Symptoms' },
    { code: 'R51', name: 'Headache', category: 'Symptoms' },
    { code: 'R10.9', name: 'Unspecified abdominal pain', category: 'Symptoms' },
    { code: 'R53.83', name: 'Fatigue', category: 'Symptoms' },
    { code: 'R42', name: 'Dizziness and giddiness', category: 'Symptoms' },
    { code: 'R11.2', name: 'Nausea with vomiting, unspecified', category: 'Symptoms' },
    { code: 'R06.02', name: 'Shortness of breath', category: 'Symptoms' },
    { code: 'R07.9', name: 'Chest pain, unspecified', category: 'Symptoms' },
    { code: 'H35.311', name: 'Nonexudative age-related macular degeneration, right eye, early dry stage', category: 'Retina - AMD' },
    { code: 'H35.312', name: 'Nonexudative age-related macular degeneration, left eye, early dry stage', category: 'Retina - AMD' },
    { code: 'H35.313', name: 'Nonexudative age-related macular degeneration, bilateral', category: 'Retina - AMD' },
    { code: 'H35.321', name: 'Exudative age-related macular degeneration, right eye', category: 'Retina - AMD' },
    { code: 'H35.322', name: 'Exudative age-related macular degeneration, left eye', category: 'Retina - AMD' },
    { code: 'H35.323', name: 'Exudative age-related macular degeneration, bilateral', category: 'Retina - AMD' },
    { code: 'E11.311', name: 'Type 2 DM with nonproliferative diabetic retinopathy, right eye', category: 'Retina - Diabetic' },
    { code: 'E11.312', name: 'Type 2 DM with nonproliferative diabetic retinopathy, left eye', category: 'Retina - Diabetic' },
    { code: 'E11.319', name: 'Type 2 DM with nonproliferative diabetic retinopathy, unspecified eye', category: 'Retina - Diabetic' },
    { code: 'E11.321', name: 'Type 2 DM with mild NPDR with macular edema, right eye', category: 'Retina - Diabetic' },
    { code: 'E11.331', name: 'Type 2 DM with moderate NPDR with macular edema, right eye', category: 'Retina - Diabetic' },
    { code: 'E11.341', name: 'Type 2 DM with severe NPDR with macular edema, right eye', category: 'Retina - Diabetic' },
    { code: 'E11.351', name: 'Type 2 DM with proliferative diabetic retinopathy, right eye', category: 'Retina - Diabetic' },
    { code: 'E11.352', name: 'Type 2 DM with proliferative diabetic retinopathy, left eye', category: 'Retina - Diabetic' },
    { code: 'E11.353', name: 'Type 2 DM with proliferative diabetic retinopathy, bilateral', category: 'Retina - Diabetic' },
    { code: 'E11.359', name: 'Type 2 DM with proliferative diabetic retinopathy, unspecified eye', category: 'Retina - Diabetic' },
    { code: 'H34.11', name: 'Central retinal artery occlusion, right eye', category: 'Retina - Vascular' },
    { code: 'H34.12', name: 'Central retinal artery occlusion, left eye', category: 'Retina - Vascular' },
    { code: 'H34.13', name: 'Central retinal artery occlusion, bilateral', category: 'Retina - Vascular' },
    { code: 'H34.21', name: 'Central retinal vein occlusion, right eye', category: 'Retina - Vascular' },
    { code: 'H34.22', name: 'Central retinal vein occlusion, left eye', category: 'Retina - Vascular' },
    { code: 'H34.23', name: 'Central retinal vein occlusion, bilateral', category: 'Retina - Vascular' },
    { code: 'H34.811', name: 'CRVO with retinal neovascularization, right eye', category: 'Retina - Vascular' },
    { code: 'H34.831', name: 'Branch retinal vein occlusion, right eye', category: 'Retina - Vascular' },
    { code: 'H34.832', name: 'Branch retinal vein occlusion, left eye', category: 'Retina - Vascular' },
    { code: 'H33.001', name: 'Retinal detachment with retinal break, right eye', category: 'Retina - Detachment' },
    { code: 'H33.002', name: 'Retinal detachment with retinal break, left eye', category: 'Retina - Detachment' },
    { code: 'H33.003', name: 'Retinal detachment with retinal break, bilateral', category: 'Retina - Detachment' },
    { code: 'H33.011', name: 'Retinal detachment with giant tear, right eye', category: 'Retina - Detachment' },
    { code: 'H33.031', name: 'Retinal detachment with dialysis, right eye', category: 'Retina - Detachment' },
    { code: 'H33.1', name: 'Retinoschisis and retinal cysts', category: 'Retina - Detachment' },
    { code: 'H33.2', name: 'Serous retinal detachment', category: 'Retina - Detachment' },
    { code: 'H33.41', name: 'Traction retinal detachment, right eye', category: 'Retina - Detachment' },
    { code: 'H35.81', name: 'Macular edema, unspecified', category: 'Retina - Macula' },
    { code: 'H35.82', name: 'Macular hole, unspecified', category: 'Retina - Macula' },
    { code: 'H35.821', name: 'Macular hole, right eye', category: 'Retina - Macula' },
    { code: 'H35.822', name: 'Macular hole, left eye', category: 'Retina - Macula' },
    { code: 'H35.83', name: 'Pseudohole of macula', category: 'Retina - Macula' },
    { code: 'H35.84', name: 'Vitreomacular adhesion', category: 'Retina - Macula' },
    { code: 'H35.85', name: 'Vitreomacular traction', category: 'Retina - Macula' },
    { code: 'H35.36', name: 'Cystoid macular edema (CME)', category: 'Retina - Macula' },
    { code: 'H35.60', name: 'Retinal hemorrhage, unspecified', category: 'Retina - Hemorrhage' },
    { code: 'H35.61', name: 'Hard exudates, unspecified', category: 'Retina - Hemorrhage' },
    { code: 'H35.62', name: 'Retinal lipid exudates', category: 'Retina - Hemorrhage' },
    { code: 'H35.7', name: 'Separation of retinal layers', category: 'Retina - Layers' },
    { code: 'H43.81', name: 'Vitreous hemorrhage', category: 'Retina - Vitreous' },
    { code: 'H43.82', name: 'Vitreous membranes and strands', category: 'Retina - Vitreous' },
    { code: 'H43.9', name: 'Disorder of vitreous body, unspecified', category: 'Retina - Vitreous' },
    { code: 'H30.011', name: 'Focal chorioretinal inflammation, right eye', category: 'Retina - Inflammation' },
    { code: 'H30.012', name: 'Focal chorioretinal inflammation, left eye', category: 'Retina - Inflammation' },
    { code: 'H30.111', name: 'Disseminated chorioretinal inflammation, right eye', category: 'Retina - Inflammation' },
    { code: 'H30.112', name: 'Disseminated chorioretinal inflammation, left eye', category: 'Retina - Inflammation' },
    { code: 'H31.111', name: 'Choroidal neovascularization, right eye', category: 'Retina - Choroid' },
    { code: 'H31.112', name: 'Choroidal neovascularization, left eye', category: 'Retina - Choroid' },
    { code: 'H35.01', name: 'Background retinopathy, right eye', category: 'Retina - Retinopathy' },
    { code: 'H35.02', name: 'Background retinopathy, left eye', category: 'Retina - Retinopathy' },
    { code: 'H35.1', name: 'Retinopathy of prematurity (ROP)', category: 'Retina - Retinopathy' },
    { code: 'H35.2', name: 'Other non-diabetic proliferative retinopathy', category: 'Retina - Retinopathy' },
    { code: 'H35.371', name: 'Drusen of optic disc, right eye', category: 'Retina - Optic Nerve' },
    { code: 'H35.372', name: 'Drusen of optic disc, left eye', category: 'Retina - Optic Nerve' },
    { code: 'H44.111', name: 'Panuveitis, right eye', category: 'Retina - Uveitis' },
    { code: 'H44.112', name: 'Panuveitis, left eye', category: 'Retina - Uveitis' },
    { code: 'H44.2A', name: 'High myopia with retinopathy', category: 'Retina - Myopia' },
    { code: 'H35.9', name: 'Unspecified retinal disorder', category: 'Retina - General' },
    { code: 'Z01.00', name: 'Encounter for eye examination with no abnormal findings', category: 'Retina - Exam' },
    // Glaucoma ICD-10 codes (H40 series)
    { code: 'H40.00', name: 'Preglaucoma, unspecified', category: 'Glaucoma - General' },
    { code: 'H40.01', name: 'Open angle with borderline findings, low risk', category: 'Glaucoma - OHT' },
    { code: 'H40.02', name: 'Open angle with borderline findings, high risk', category: 'Glaucoma - OHT' },
    { code: 'H40.10X0', name: 'Unspecified open-angle glaucoma, stage unspecified', category: 'Glaucoma - POAG' },
    { code: 'H40.10X1', name: 'Unspecified open-angle glaucoma, mild stage', category: 'Glaucoma - POAG' },
    { code: 'H40.10X2', name: 'Unspecified open-angle glaucoma, moderate stage', category: 'Glaucoma - POAG' },
    { code: 'H40.10X3', name: 'Unspecified open-angle glaucoma, severe stage', category: 'Glaucoma - POAG' },
    { code: 'H40.111', name: 'Primary open-angle glaucoma, right eye, mild stage', category: 'Glaucoma - POAG' },
    { code: 'H40.112', name: 'Primary open-angle glaucoma, left eye, mild stage', category: 'Glaucoma - POAG' },
    { code: 'H40.113', name: 'Primary open-angle glaucoma, bilateral, mild stage', category: 'Glaucoma - POAG' },
    { code: 'H40.114', name: 'Primary open-angle glaucoma, right eye, moderate stage', category: 'Glaucoma - POAG' },
    { code: 'H40.115', name: 'Primary open-angle glaucoma, left eye, moderate stage', category: 'Glaucoma - POAG' },
    { code: 'H40.116', name: 'Primary open-angle glaucoma, bilateral, moderate stage', category: 'Glaucoma - POAG' },
    { code: 'H40.117', name: 'Primary open-angle glaucoma, right eye, severe stage', category: 'Glaucoma - POAG' },
    { code: 'H40.118', name: 'Primary open-angle glaucoma, left eye, severe stage', category: 'Glaucoma - POAG' },
    { code: 'H40.119', name: 'Primary open-angle glaucoma, bilateral, severe stage', category: 'Glaucoma - POAG' },
    { code: 'H40.121', name: 'Low-tension glaucoma, right eye, mild stage', category: 'Glaucoma - NTG' },
    { code: 'H40.122', name: 'Low-tension glaucoma, left eye, mild stage', category: 'Glaucoma - NTG' },
    { code: 'H40.123', name: 'Low-tension glaucoma, bilateral, mild stage', category: 'Glaucoma - NTG' },
    { code: 'H40.124', name: 'Low-tension glaucoma, right eye, moderate stage', category: 'Glaucoma - NTG' },
    { code: 'H40.125', name: 'Low-tension glaucoma, left eye, moderate stage', category: 'Glaucoma - NTG' },
    { code: 'H40.126', name: 'Low-tension glaucoma, bilateral, moderate stage', category: 'Glaucoma - NTG' },
    { code: 'H40.127', name: 'Low-tension glaucoma, right eye, severe stage', category: 'Glaucoma - NTG' },
    { code: 'H40.128', name: 'Low-tension glaucoma, left eye, severe stage', category: 'Glaucoma - NTG' },
    { code: 'H40.129', name: 'Low-tension glaucoma, bilateral, severe stage', category: 'Glaucoma - NTG' },
    { code: 'H40.131', name: 'Pigmentary glaucoma, right eye, mild stage', category: 'Glaucoma - Pigmentary' },
    { code: 'H40.132', name: 'Pigmentary glaucoma, left eye, mild stage', category: 'Glaucoma - Pigmentary' },
    { code: 'H40.133', name: 'Pigmentary glaucoma, bilateral', category: 'Glaucoma - Pigmentary' },
    { code: 'H40.141', name: 'Capsular glaucoma with pseudoexfoliation, right eye', category: 'Glaucoma - PEXG' },
    { code: 'H40.142', name: 'Capsular glaucoma with pseudoexfoliation, left eye', category: 'Glaucoma - PEXG' },
    { code: 'H40.143', name: 'Capsular glaucoma with pseudoexfoliation, bilateral', category: 'Glaucoma - PEXG' },
    { code: 'H40.15', name: 'Residual stage of open-angle glaucoma', category: 'Glaucoma - POAG' },
    { code: 'H40.20X0', name: 'Unspecified primary angle-closure glaucoma, stage unspecified', category: 'Glaucoma - PACG' },
    { code: 'H40.20X1', name: 'Unspecified primary angle-closure glaucoma, mild stage', category: 'Glaucoma - PACG' },
    { code: 'H40.20X2', name: 'Unspecified primary angle-closure glaucoma, moderate stage', category: 'Glaucoma - PACG' },
    { code: 'H40.20X3', name: 'Unspecified primary angle-closure glaucoma, severe stage', category: 'Glaucoma - PACG' },
    { code: 'H40.211', name: 'Acute angle-closure glaucoma, right eye', category: 'Glaucoma - PACG' },
    { code: 'H40.212', name: 'Acute angle-closure glaucoma, left eye', category: 'Glaucoma - PACG' },
    { code: 'H40.213', name: 'Acute angle-closure glaucoma, bilateral', category: 'Glaucoma - PACG' },
    { code: 'H40.221', name: 'Chronic angle-closure glaucoma, right eye', category: 'Glaucoma - PACG' },
    { code: 'H40.222', name: 'Chronic angle-closure glaucoma, left eye', category: 'Glaucoma - PACG' },
    { code: 'H40.223', name: 'Chronic angle-closure glaucoma, bilateral', category: 'Glaucoma - PACG' },
    { code: 'H40.231', name: 'Intermittent angle-closure glaucoma, right eye', category: 'Glaucoma - PACG' },
    { code: 'H40.232', name: 'Intermittent angle-closure glaucoma, left eye', category: 'Glaucoma - PACG' },
    { code: 'H40.233', name: 'Intermittent angle-closure glaucoma, bilateral', category: 'Glaucoma - PACG' },
    { code: 'H40.24', name: 'Residual stage of angle-closure glaucoma', category: 'Glaucoma - PACG' },
    { code: 'H40.3', name: 'Glaucoma secondary to eye trauma', category: 'Glaucoma - Secondary' },
    { code: 'H40.4', name: 'Glaucoma secondary to eye inflammation', category: 'Glaucoma - Secondary' },
    { code: 'H40.5', name: 'Glaucoma secondary to other eye disorders', category: 'Glaucoma - Secondary' },
    { code: 'H40.6', name: 'Glaucoma secondary to drugs', category: 'Glaucoma - Secondary' },
    { code: 'H40.81', name: 'Glaucoma with increased episcleral venous pressure', category: 'Glaucoma - Other' },
    { code: 'H40.82', name: 'Hypersecretion glaucoma', category: 'Glaucoma - Other' },
    { code: 'H40.83', name: 'Aqueous misdirection (Malignant glaucoma)', category: 'Glaucoma - Other' },
    { code: 'H40.89', name: 'Other specified glaucoma', category: 'Glaucoma - Other' },
    { code: 'H40.9', name: 'Unspecified glaucoma', category: 'Glaucoma - Other' },
    { code: 'Q15.0', name: 'Congenital glaucoma (Buphthalmos)', category: 'Glaucoma - Congenital' },
  ];

  for (const icd of icd10Codes) {
    await prisma.icd10Code.upsert({
      where: { code: icd.code },
      update: { name: icd.name, category: icd.category },
      create: icd,
    });
  }

  const labTests = [
    { code: 'CBC', name: 'Complete Blood Count', price: 50, category: 'Hematology', specimen: 'Blood', unit: '', refRangeText: '' },
    { code: 'HGB', name: 'Hemoglobin', price: 25, category: 'Hematology', specimen: 'Blood', unit: 'g/dL', refRangeText: '13.5-17.5' },
    { code: 'WBC', name: 'White Blood Cell Count', price: 25, category: 'Hematology', specimen: 'Blood', unit: 'x10^9/L', refRangeText: '4.5-11.0' },
    { code: 'PLT', name: 'Platelet Count', price: 25, category: 'Hematology', specimen: 'Blood', unit: 'x10^9/L', refRangeText: '150-400' },
    { code: 'HCT', name: 'Hematocrit', price: 25, category: 'Hematology', specimen: 'Blood', unit: '%', refRangeText: '38-50' },
    { code: 'GLU', name: 'Glucose (Fasting)', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '70-100' },
    { code: 'GLU_R', name: 'Glucose (Random)', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '<140' },
    { code: 'HB1AC', name: 'HbA1c', price: 80, category: 'Chemistry', specimen: 'Blood', unit: '%', refRangeText: '<5.7' },
    { code: 'LIPID', name: 'Lipid Panel', price: 100, category: 'Chemistry', specimen: 'Serum', unit: '', refRangeText: '' },
    { code: 'TCHOL', name: 'Total Cholesterol', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '<200' },
    { code: 'HDL', name: 'HDL Cholesterol', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '>40' },
    { code: 'LDL', name: 'LDL Cholesterol', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '<100' },
    { code: 'TG', name: 'Triglycerides', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '<150' },
    { code: 'BUN', name: 'Blood Urea Nitrogen', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '7-20' },
    { code: 'CREA', name: 'Creatinine', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '0.6-1.2' },
    { code: 'EGFR', name: 'eGFR', price: 40, category: 'Chemistry', specimen: 'Serum', unit: 'mL/min', refRangeText: '>60' },
    { code: 'NA', name: 'Sodium', price: 35, category: 'Electrolytes', specimen: 'Serum', unit: 'mmol/L', refRangeText: '136-145' },
    { code: 'K', name: 'Potassium', price: 35, category: 'Electrolytes', specimen: 'Serum', unit: 'mmol/L', refRangeText: '3.5-5.1' },
    { code: 'CL', name: 'Chloride', price: 35, category: 'Electrolytes', specimen: 'Serum', unit: 'mmol/L', refRangeText: '98-107' },
    { code: 'CO2', name: 'CO2 (Bicarbonate)', price: 35, category: 'Electrolytes', specimen: 'Serum', unit: 'mmol/L', refRangeText: '22-29' },
    { code: 'LFT', name: 'Liver Function Panel', price: 120, category: 'Chemistry', specimen: 'Serum', unit: '', refRangeText: '' },
    { code: 'ALT', name: 'ALT (SGPT)', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'U/L', refRangeText: '10-40' },
    { code: 'AST', name: 'AST (SGOT)', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'U/L', refRangeText: '10-40' },
    { code: 'ALP', name: 'Alkaline Phosphatase', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'U/L', refRangeText: '44-147' },
    { code: 'TBIL', name: 'Total Bilirubin', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '0.1-1.2' },
    { code: 'TPRO', name: 'Total Protein', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'g/dL', refRangeText: '6.0-8.3' },
    { code: 'ALB', name: 'Albumin', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'g/dL', refRangeText: '3.5-5.0' },
    { code: 'TSH', name: 'TSH', price: 90, category: 'Hormones', specimen: 'Serum', unit: 'mIU/L', refRangeText: '0.4-4.0' },
    { code: 'FT4', name: 'Free T4', price: 80, category: 'Hormones', specimen: 'Serum', unit: 'ng/dL', refRangeText: '0.8-1.8' },
    { code: 'FT3', name: 'Free T3', price: 80, category: 'Hormones', specimen: 'Serum', unit: 'pg/mL', refRangeText: '2.3-4.2' },
    { code: 'INR', name: 'INR (PT)', price: 45, category: 'Coagulation', specimen: 'Plasma', unit: '', refRangeText: '0.9-1.2' },
    { code: 'PTT', name: 'PTT (aPTT)', price: 50, category: 'Coagulation', specimen: 'Plasma', unit: 'sec', refRangeText: '25-35' },
    { code: 'UA', name: 'Urinalysis', price: 40, category: 'Urinalysis', specimen: 'Urine', unit: '', refRangeText: '' },
    { code: 'U_GLU', name: 'Urine Glucose', price: 20, category: 'Urinalysis', specimen: 'Urine', unit: '', refRangeText: 'Negative' },
    { code: 'U_PRO', name: 'Urine Protein', price: 20, category: 'Urinalysis', specimen: 'Urine', unit: '', refRangeText: 'Negative' },
    { code: 'U_BLD', name: 'Urine Blood', price: 20, category: 'Urinalysis', specimen: 'Urine', unit: '', refRangeText: 'Negative' },
    { code: 'U_KET', name: 'Urine Ketones', price: 20, category: 'Urinalysis', specimen: 'Urine', unit: '', refRangeText: 'Negative' },
    { code: 'U_LEU', name: 'Urine Leukocytes', price: 20, category: 'Urinalysis', specimen: 'Urine', unit: '', refRangeText: 'Negative' },
    { code: 'U_NIT', name: 'Urine Nitrite', price: 20, category: 'Urinalysis', specimen: 'Urine', unit: '', refRangeText: 'Negative' },
    { code: 'CRP', name: 'C-Reactive Protein', price: 60, category: 'Chemistry', specimen: 'Serum', unit: 'mg/L', refRangeText: '<5' },
    { code: 'ESR', name: 'Erythrocyte Sedimentation Rate', price: 35, category: 'Hematology', specimen: 'Blood', unit: 'mm/hr', refRangeText: '<20' },
    { code: 'FER', name: 'Ferritin', price: 85, category: 'Chemistry', specimen: 'Serum', unit: 'ng/mL', refRangeText: '20-250' },
    { code: 'VITD', name: 'Vitamin D (25-OH)', price: 120, category: 'Chemistry', specimen: 'Serum', unit: 'ng/mL', refRangeText: '30-100' },
    { code: 'VITB12', name: 'Vitamin B12', price: 100, category: 'Chemistry', specimen: 'Serum', unit: 'pg/mL', refRangeText: '200-900' },
    { code: 'FOL', name: 'Folate', price: 70, category: 'Chemistry', specimen: 'Serum', unit: 'ng/mL', refRangeText: '3-17' },
    { code: 'URIC', name: 'Uric Acid', price: 30, category: 'Chemistry', specimen: 'Serum', unit: 'mg/dL', refRangeText: '3.5-7.2' },
    { code: 'MG', name: 'Magnesium', price: 35, category: 'Electrolytes', specimen: 'Serum', unit: 'mg/dL', refRangeText: '1.7-2.2' },
    { code: 'CA', name: 'Calcium', price: 35, category: 'Electrolytes', specimen: 'Serum', unit: 'mg/dL', refRangeText: '8.5-10.5' },
    { code: 'PHOS', name: 'Phosphorus', price: 35, category: 'Electrolytes', specimen: 'Serum', unit: 'mg/dL', refRangeText: '2.5-4.5' },
    { code: 'AMY', name: 'Amylase', price: 50, category: 'Chemistry', specimen: 'Serum', unit: 'U/L', refRangeText: '28-100' },
    { code: 'LIP', name: 'Lipase', price: 55, category: 'Chemistry', specimen: 'Serum', unit: 'U/L', refRangeText: '13-60' },
    { code: 'CK', name: 'Creatine Kinase', price: 45, category: 'Chemistry', specimen: 'Serum', unit: 'U/L', refRangeText: '55-170' },
    { code: 'TNT', name: 'Troponin T', price: 150, category: 'Chemistry', specimen: 'Serum', unit: 'ng/L', refRangeText: '<14' },
    { code: 'TNI', name: 'Troponin I', price: 150, category: 'Chemistry', specimen: 'Serum', unit: 'ng/mL', refRangeText: '<0.04' },
    { code: 'BNP', name: 'BNP', price: 180, category: 'Chemistry', specimen: 'Plasma', unit: 'pg/mL', refRangeText: '<100' },
    { code: 'ABG', name: 'Arterial Blood Gas', price: 100, category: 'Blood Gas', specimen: 'Arterial Blood', unit: '', refRangeText: '' },
  ];

  for (const test of labTests) {
    const { price, ...testData } = test;
    await prisma.diagnosticTest.upsert({
      where: { orderType_code: { orderType: 'LAB', code: test.code } },
      update: { name: test.name, category: test.category, specimen: test.specimen, unit: test.unit, refRangeText: test.refRangeText, price: test.price || null },
      create: { ...testData, price: price || null, orderType: 'LAB' },
    });
  }

  const departments = [
    { slug: 'medicine-dept', name: 'Medicine Clinic', type: 'CLINIC', clinicId: clinics[0].id },
    { slug: 'ent-dept', name: 'ENT Clinic', type: 'CLINIC', clinicId: clinics[1].id },
    { slug: 'dental-dept', name: 'Dental Clinic', type: 'CLINIC', clinicId: clinics[2].id },
    { slug: 'retina-dept', name: 'Retina Clinic', type: 'CLINIC', clinicId: clinics[3].id },
    { slug: 'glaucoma-dept', name: 'Glaucoma Clinic', type: 'CLINIC', clinicId: clinics[4].id },
    { slug: 'orbit-dept', name: 'Orbit Clinic', type: 'CLINIC', clinicId: clinics[5].id },
    { slug: 'peds-ophth-dept', name: 'Pediatrics Ophthalmology', type: 'CLINIC', clinicId: clinics[6].id },
    { slug: 'gen-ophth-dept', name: 'General Ophthalmology', type: 'CLINIC', clinicId: clinics[7].id },
    { slug: 'optometry-dept', name: 'Optometry Clinic', type: 'CLINIC', clinicId: clinics[8].id },
    { slug: 'pharmacy-dept', name: 'Pharmacy', type: 'PHARMACY', clinicId: null },
    { slug: 'optics-dept', name: 'Optics', type: 'OTHER', clinicId: null },
    { slug: 'lab-dept', name: 'Laboratory', type: 'LAB', clinicId: null },
    { slug: 'surgery-dept', name: 'Surgery', type: 'SURGERY', clinicId: null },
    { slug: 'admin-dept', name: 'Administration', type: 'ADMIN', clinicId: null },
    { slug: 'hr-dept', name: 'Human Resources', type: 'HR', clinicId: null },
    { slug: 'finance-dept', name: 'Finance', type: 'FINANCE', clinicId: null },
    { slug: 'it-dept', name: 'IT', type: 'IT', clinicId: null },
    { slug: 'nursing-dept', name: 'Nursing', type: 'NURSING', clinicId: null },
    { slug: 'hospital-dept', name: 'Hospital Operations', type: 'OTHER', clinicId: null },
  ];

  for (const dept of departments) {
    await prisma.department.upsert({
      where: { slug: dept.slug },
      update: { name: dept.name, type: dept.type, clinicId: dept.clinicId },
      create: dept,
    });
  }

  console.log(`Seeded ${labTests.length} lab tests.`);
  console.log(`Seeded ${icd10Codes.length} ICD-10 codes.`);
  console.log(`Seeded ${departments.length} departments.`);

  // Seed cost centers (one per department)
  const allDepts = await prisma.department.findMany();
  const costCenters = [
    { code: 'CC-MED', name: 'Medicine Clinic Cost Center', deptSlug: 'medicine-dept' },
    { code: 'CC-ENT', name: 'ENT Clinic Cost Center', deptSlug: 'ent-dept' },
    { code: 'CC-DEN', name: 'Dental Clinic Cost Center', deptSlug: 'dental-dept' },
    { code: 'CC-RET', name: 'Retina Clinic Cost Center', deptSlug: 'retina-dept' },
    { code: 'CC-GLA', name: 'Glaucoma Clinic Cost Center', deptSlug: 'glaucoma-dept' },
    { code: 'CC-ORB', name: 'Orbit Clinic Cost Center', deptSlug: 'orbit-dept' },
    { code: 'CC-PED', name: 'Pediatrics Ophthalmology Cost Center', deptSlug: 'peds-ophth-dept' },
    { code: 'CC-GOP', name: 'General Ophthalmology Cost Center', deptSlug: 'gen-ophth-dept' },
    { code: 'CC-OPT', name: 'Optometry Clinic Cost Center', deptSlug: 'optometry-dept' },
    { code: 'CC-PHA', name: 'Pharmacy Cost Center', deptSlug: 'pharmacy-dept' },
    { code: 'CC-OCS', name: 'Optics Cost Center', deptSlug: 'optics-dept' },
    { code: 'CC-LAB', name: 'Laboratory Cost Center', deptSlug: 'lab-dept' },
    { code: 'CC-SRG', name: 'Surgery Cost Center', deptSlug: 'surgery-dept' },
    { code: 'CC-ADM', name: 'Administration Cost Center', deptSlug: 'admin-dept' },
    { code: 'CC-HR', name: 'Human Resources Cost Center', deptSlug: 'hr-dept' },
    { code: 'CC-FIN', name: 'Finance Cost Center', deptSlug: 'finance-dept' },
    { code: 'CC-IT', name: 'IT Cost Center', deptSlug: 'it-dept' },
    { code: 'CC-NUR', name: 'Nursing Cost Center', deptSlug: 'nursing-dept' },
    { code: 'CC-HOS', name: 'Hospital Operations Cost Center', deptSlug: 'hospital-dept' },
  ];

  for (const cc of costCenters) {
    const dept = allDepts.find(d => d.slug === cc.deptSlug);
    if (!dept) continue;
    await prisma.costCenter.upsert({
      where: { code: cc.code },
      update: { name: cc.name, departmentId: dept.id },
      create: { code: cc.code, name: cc.name, departmentId: dept.id },
    });
  }

  console.log(`Seeded ${costCenters.length} cost centers.`);
  console.log('Seed complete.');
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
