export const PERMISSIONS_LIST = [
  { key: 'patient:read', label: 'View Patients' },
  { key: 'patient:create', label: 'Create Patients' },
  { key: 'patient:update', label: 'Update Patients' },
  { key: 'clinical:read', label: 'View Clinical Records' },
  { key: 'clinical:write', label: 'Write Clinical Records' },
  { key: 'appointment:read', label: 'View Appointments' },
  { key: 'appointment:write', label: 'Manage Appointments' },
  { key: 'pharmacy:read', label: 'View Pharmacy' },
  { key: 'pharmacy:write', label: 'Manage Pharmacy' },
  { key: 'optics:read', label: 'View Optics' },
  { key: 'optics:write', label: 'Manage Optics' },
  { key: 'surgery:read', label: 'View Surgeries' },
  { key: 'surgery:write', label: 'Manage Surgeries' },
  { key: 'accounting:read', label: 'View Accounting' },
  { key: 'accounting:write', label: 'Manage Accounting' },
  { key: 'warehouse:read', label: 'View Warehouse' },
  { key: 'warehouse:write', label: 'Manage Warehouse' },
  { key: 'admin:users', label: 'Manage Users' },
  { key: 'admin:rbac', label: 'Manage Roles' },
  { key: 'hr:read', label: 'View HR' },
  { key: 'hr:write', label: 'Manage HR' },
  { key: 'diagnostics:read', label: 'View Lab & Diagnostics' },
  { key: 'diagnostics:order', label: 'Order Lab Tests' },
  { key: 'diagnostics:write', label: 'Perform Lab Work' },
  { key: 'diagnostics:results', label: 'Enter Lab Results' },
  { key: 'diagnostics:catalog', label: 'Manage Test Catalog' },
  { key: 'inventory:read', label: 'View Inventory Dashboard' },
  { key: 'inventory:write', label: 'Manage Inventory' },
  { key: 'purchase:read', label: 'View Purchases' },
  { key: 'purchase:write', label: 'Manage Purchases' },
  { key: 'approval:read', label: 'View Approvals' },
  { key: 'approval:write', label: 'Approve/Reject' },
  { key: 'asset:read', label: 'View Fixed Assets' },
  { key: 'asset:write', label: 'Manage Fixed Assets' },
  { key: 'notification:read', label: 'View Notifications' },
  { key: 'preoperative:read', label: 'View Preoperative' },
  { key: 'preoperative:write', label: 'Manage Preoperative' },
  { key: 'optic_lab:read', label: 'View Optic Lab' },
  { key: 'optic_lab:write', label: 'Manage Optic Lab' },
  { key: 'ward:read', label: 'View Wards' },
  { key: 'ward:write', label: 'Manage Wards' },
  { key: 'pricing:read', label: 'View Pricing' },
  { key: 'pricing:write', label: 'Manage Pricing' },
];
