export const PERMISSIONS_LIST = [
  { key: 'patient:read', label: 'View Patients' },
  { key: 'patient:create', label: 'Create Patients' },
  { key: 'patient:update', label: 'Update Patients' },
  { key: 'clinical:read', label: 'View Clinical Records' },
  { key: 'clinical:write', label: 'Write Clinical Records' },
  { key: 'appointment:read', label: 'View Appointments' },
  { key: 'appointment:write', label: 'Manage Appointments' },
  { key: 'pharmacy:read', label: 'View Pharmacy' },
  { key: 'pharmacy:write', label: 'Manage Pharmacy' },
  { key: 'optics:read', label: 'View Optics' },
  { key: 'optics:write', label: 'Manage Optics' },
  { key: 'surgery:read', label: 'View Surgeries' },
  { key: 'surgery:write', label: 'Manage Surgeries' },
  { key: 'accounting:read', label: 'View Accounting' },
  { key: 'accounting:write', label: 'Manage Accounting' },
  { key: 'warehouse:read', label: 'View Warehouse' },
  { key: 'warehouse:write', label: 'Manage Warehouse' },
  { key: 'admin:users', label: 'Manage Users' },
  { key: 'admin:rbac', label: 'Manage Roles' },
  { key: 'hr:read', label: 'View HR' },
  { key: 'hr:write', label: 'Manage HR' },
  { key: 'diagnostics:read', label: 'View Lab & Diagnostics' },
  { key: 'diagnostics:order', label: 'Order Lab Tests' },
  { key: 'diagnostics:write', label: 'Perform Lab Work' },
  { key: 'diagnostics:results', label: 'Enter Lab Results' },
  { key: 'diagnostics:catalog', label: 'Manage Test Catalog' },
];
