import { Router } from 'express';
import summaryRoutes from './routes/summary.routes.js';
import transactionRoutes from './routes/transactions.routes.js';
import expenseRoutes from './routes/expenses.routes.js';
import shiftRoutes from './routes/shifts.routes.js';
import debtRoutes from './routes/debts.routes.js';
import cashMovementRoutes from './routes/cashMovements.routes.js';
import serviceCatalogRoutes from './routes/serviceCatalog.routes.js';
import invoiceRoutes from './routes/invoices.routes.js';
import journalRoutes from './routes/journal.routes.js';
import fixedAssetsRoutes from './routes/fixedAssets.routes.js';
import costCentersRoutes from './routes/costCenters.routes.js';
import paymentPlanRoutes from './routes/paymentPlans.routes.js';
import arAgingRoutes from './routes/arAging.routes.js';
import creditMemoRoutes from './routes/creditMemos.routes.js';
import refundRoutes from './routes/refunds.routes.js';
import writeoffRoutes from './routes/writeoffs.routes.js';
import statementRoutes from './routes/statements.routes.js';

const router = Router();
router.use('/', summaryRoutes);
router.use('/transactions', transactionRoutes);
router.use('/expenses', expenseRoutes);
router.use('/shifts', shiftRoutes);
router.use('/debts', debtRoutes);
router.use('/cash-movements', cashMovementRoutes);
router.use('/service-items', serviceCatalogRoutes);
router.use('/invoices', invoiceRoutes);
router.use('/journal', journalRoutes);
router.use('/fixed-assets', fixedAssetsRoutes);
router.use('/cost-centers', costCentersRoutes);
router.use('/payment-plans', paymentPlanRoutes);
router.use('/ar-aging', arAgingRoutes);
router.use('/credit-memos', creditMemoRoutes);
router.use('/refunds', refundRoutes);
router.use('/writeoffs', writeoffRoutes);
router.use('/statements', statementRoutes);

export default router;
