/**
 * Role definitions with granular feature-level permissions.
 * Structure: { "module:action": true/false }
 */
export const PERMISSIONS = {
  PATIENT_READ: 'patient:read',
  PATIENT_CREATE: 'patient:create',
  PATIENT_UPDATE: 'patient:update',
  CLINICAL_READ: 'clinical:read',
  CLINICAL_WRITE: 'clinical:write',
  APPOINTMENT_READ: 'appointment:read',
  APPOINTMENT_WRITE: 'appointment:write',
  PHARMACY_READ: 'pharmacy:read',
  PHARMACY_WRITE: 'pharmacy:write',
  OPTICS_READ: 'optics:read',
  OPTICS_WRITE: 'optics:write',
  SURGERY_READ: 'surgery:read',
  SURGERY_WRITE: 'surgery:write',
  ACCOUNTING_READ: 'accounting:read',
  ACCOUNTING_WRITE: 'accounting:write',
  WAREHOUSE_READ: 'warehouse:read',
  WAREHOUSE_WRITE: 'warehouse:write',
  ADMIN_USERS: 'admin:users',
  ADMIN_RBAC: 'admin:rbac',
  HR_READ: 'hr:read',
  HR_WRITE: 'hr:write',
  DIAGNOSTICS_READ: 'diagnostics:read',
  DIAGNOSTICS_ORDER: 'diagnostics:order',
  DIAGNOSTICS_WRITE: 'diagnostics:write',
  DIAGNOSTICS_RESULTS: 'diagnostics:results',
  DIAGNOSTICS_CATALOG: 'diagnostics:catalog',
  INVENTORY_READ: 'inventory:read',
  INVENTORY_WRITE: 'inventory:write',
  PURCHASE_READ: 'purchase:read',
  PURCHASE_WRITE: 'purchase:write',
  APPROVAL_READ: 'approval:read',
  APPROVAL_WRITE: 'approval:write',
  ASSET_READ: 'asset:read',
  ASSET_WRITE: 'asset:write',
  NOTIFICATION_READ: 'notification:read',
  OPTIC_LAB_READ: 'optic_lab:read',
  OPTIC_LAB_WRITE: 'optic_lab:write',
  PREOP_READ: 'preoperative:read',
  PREOP_WRITE: 'preoperative:write',
  WARD_READ: 'ward:read',
  WARD_WRITE: 'ward:write',
  PRICING_READ: 'pricing:read',
  PRICING_WRITE: 'pricing:write',
};

export const DEFAULT_ROLES = {
  SUPER_ADMIN: {
    name: 'Super Admin',
    permissions: [...Object.values(PERMISSIONS)],
  },
  DOCTOR: {
    name: 'Doctor',
    permissions: [
      PERMISSIONS.PATIENT_READ,
      PERMISSIONS.PATIENT_CREATE,
      PERMISSIONS.CLINICAL_READ,
      PERMISSIONS.CLINICAL_WRITE,
      PERMISSIONS.APPOINTMENT_READ,
      PERMISSIONS.APPOINTMENT_WRITE,
      PERMISSIONS.SURGERY_READ,
      PERMISSIONS.WAREHOUSE_READ,
      PERMISSIONS.DIAGNOSTICS_READ,
      PERMISSIONS.DIAGNOSTICS_ORDER,
      PERMISSIONS.PREOP_READ,
      PERMISSIONS.PREOP_WRITE,
      PERMISSIONS.WARD_READ,
    ],
  },
  NURSE: {
    name: 'Nurse',
    permissions: [
      PERMISSIONS.PATIENT_READ,
      PERMISSIONS.CLINICAL_READ,
      PERMISSIONS.APPOINTMENT_READ,
      PERMISSIONS.APPOINTMENT_WRITE,
      PERMISSIONS.WARD_READ,
      PERMISSIONS.WARD_WRITE,
    ],
  },
  PREOP_OFFICE: {
    name: 'PreOp Office',
    permissions: [
      PERMISSIONS.PATIENT_READ,
      PERMISSIONS.CLINICAL_READ,
      PERMISSIONS.APPOINTMENT_READ,
      PERMISSIONS.APPOINTMENT_WRITE,
      PERMISSIONS.PREOP_READ,
      PERMISSIONS.PREOP_WRITE,
      PERMISSIONS.WARD_READ,
      PERMISSIONS.WARD_WRITE,
      PERMISSIONS.SURGERY_READ,
      PERMISSIONS.SURGERY_WRITE,
    ],
  },
  RECEPTIONIST: {
    name: 'Receptionist',
    permissions: [
      PERMISSIONS.PATIENT_READ,
      PERMISSIONS.PATIENT_CREATE,
      PERMISSIONS.PATIENT_UPDATE,
      PERMISSIONS.APPOINTMENT_READ,
      PERMISSIONS.APPOINTMENT_WRITE,
      PERMISSIONS.ACCOUNTING_READ,
      PERMISSIONS.PREOP_READ,
    ],
  },
  PHARMACIST: {
    name: 'Pharmacist',
    permissions: [
      PERMISSIONS.PATIENT_READ,
      PERMISSIONS.CLINICAL_READ,
      PERMISSIONS.PHARMACY_READ,
      PERMISSIONS.PHARMACY_WRITE,
    ],
  },
  OPTICIAN: {
    name: 'Optician',
    permissions: [
      PERMISSIONS.PATIENT_READ,
      PERMISSIONS.OPTICS_READ,
      PERMISSIONS.OPTICS_WRITE,
    ],
  },
  ACCOUNTANT: {
    name: 'Accountant',
    permissions: [
      PERMISSIONS.ACCOUNTING_READ,
      PERMISSIONS.ACCOUNTING_WRITE,
      PERMISSIONS.PREOP_READ,
    ],
  },
  HR_MANAGER: {
    name: 'HR Manager',
    permissions: [
      PERMISSIONS.HR_READ,
      PERMISSIONS.HR_WRITE,
    ],
  },
  LAB_TECHNICIAN: {
    name: 'Lab Technician',
    permissions: [
      PERMISSIONS.PATIENT_READ,
      PERMISSIONS.DIAGNOSTICS_READ,
      PERMISSIONS.DIAGNOSTICS_WRITE,
      PERMISSIONS.DIAGNOSTICS_RESULTS,
    ],
  },
  LAB_ADMIN: {
    name: 'Lab Admin',
    permissions: [
      PERMISSIONS.PATIENT_READ,
      PERMISSIONS.DIAGNOSTICS_READ,
      PERMISSIONS.DIAGNOSTICS_ORDER,
      PERMISSIONS.DIAGNOSTICS_WRITE,
      PERMISSIONS.DIAGNOSTICS_RESULTS,
      PERMISSIONS.DIAGNOSTICS_CATALOG,
    ],
  },
  INVENTORY_MANAGER: {
    name: 'Inventory Manager',
    permissions: [
      PERMISSIONS.INVENTORY_READ,
      PERMISSIONS.INVENTORY_WRITE,
      PERMISSIONS.PHARMACY_READ,
      PERMISSIONS.PHARMACY_WRITE,
      PERMISSIONS.OPTICS_READ,
      PERMISSIONS.OPTICS_WRITE,
      PERMISSIONS.WAREHOUSE_READ,
      PERMISSIONS.WAREHOUSE_WRITE,
      PERMISSIONS.PURCHASE_READ,
      PERMISSIONS.ASSET_READ,
      PERMISSIONS.NOTIFICATION_READ,
    ],
  },
  PROCUREMENT_MANAGER: {
    name: 'Procurement Manager',
    permissions: [
      PERMISSIONS.PURCHASE_READ,
      PERMISSIONS.PURCHASE_WRITE,
      PERMISSIONS.PHARMACY_READ,
      PERMISSIONS.OPTICS_READ,
      PERMISSIONS.INVENTORY_READ,
      PERMISSIONS.WAREHOUSE_READ,
      PERMISSIONS.NOTIFICATION_READ,
    ],
  },
  HOSPITAL_DIRECTOR: {
    name: 'Hospital Director',
    permissions: [
      PERMISSIONS.PURCHASE_READ,
      PERMISSIONS.APPROVAL_READ,
      PERMISSIONS.APPROVAL_WRITE,
      PERMISSIONS.ACCOUNTING_READ,
      PERMISSIONS.NOTIFICATION_READ,
    ],
  },
  CFO: {
    name: 'CFO',
    permissions: [
      PERMISSIONS.PURCHASE_READ,
      PERMISSIONS.APPROVAL_READ,
      PERMISSIONS.APPROVAL_WRITE,
      PERMISSIONS.ACCOUNTING_READ,
      PERMISSIONS.ACCOUNTING_WRITE,
      PERMISSIONS.ASSET_READ,
      PERMISSIONS.ASSET_WRITE,
      PERMISSIONS.NOTIFICATION_READ,
    ],
  },
  CEO: {
    name: 'CEO',
    permissions: [
      PERMISSIONS.PURCHASE_READ,
      PERMISSIONS.APPROVAL_READ,
      PERMISSIONS.APPROVAL_WRITE,
      PERMISSIONS.ACCOUNTING_READ,
      PERMISSIONS.ACCOUNTING_WRITE,
      PERMISSIONS.ASSET_READ,
      PERMISSIONS.ASSET_WRITE,
      PERMISSIONS.NOTIFICATION_READ,
    ],
  },
  OPTIC_LAB: {
    name: 'OpticLab',
    permissions: [
      PERMISSIONS.PATIENT_READ,
      PERMISSIONS.OPTIC_LAB_READ,
      PERMISSIONS.OPTIC_LAB_WRITE,
    ],
  },
};
